### ISSUE TITLE
About vertical whitespace replacement

### ISSUE THREAD

**Issue by saidie** [rjbs/Email-Simple#5]
Hi,
I'm having a little trouble with the warning at https://github.com/rjbs/Email-Simple/blob/master/lib/Email/Simple/Creator.pm#L22 .

The folding of header is defined valid in RFC 2822, you know. Also, the number of characters in a line is limited. So, why do you replace the new lines with whitespace?

If there is some reason, an inevitable warning would not be good. It might be better to provide option.

**Comment by SteveTheTechie** [comment]
Sorry for commenting on a closed issue, but this warning is driving me nuts.

"replaced vertical whitespace in Subject header with space; this will become fatal in a future version at /var/www/cgi-bin/FTH_email.pl line 41"

I agree with the original poster... provide an option or a method to deal with this.  Don't just spit a warning out, give us a way to prevent the warning from happening in the first place.  Since your parser operation has a dependency on certain characters being filtered out, it makes more sense for you to provide a method or an option to filter out those characters.

**Comment by rjbs** [comment]
Finding vertical whitespace in a header is pathological.  I don't think there's an obvious way to deal with this in a generic way.  My guess is that most of the time it's a big mistake being made by the programmer.

If the programmer is sure that any vertical space should be whitespace then (on a suitably modern perl) all that's needed is:

```perl
$header_str =~ s/\v+/\x20/g;
```
…but I think that doing this preemptively would mask more serious bugs than it would solve anything.  What specific kind of input is causing you this problem?  (The path in your report makes me think that you're not chomping or something.)

**Comment by lukec** [comment]
Hello - I am also running into this issue now, and I am not clear on how I can fix it.

I added utf8/base64 encoding of our subject lines, and now longer subject lines get folded and we get this warning.  The email ends up looking like:

  Subject:
   =?utf-8?B?'UmVDb2xsZWN0IEJ1bGt5IEl0ZW0gLSBEYWlseSBSZXBvcnQgMjAxNi0wMS0xMA== ?=

I'm using `Email::MIME->create_html()` to create my email.  I'm not clear what I should be doing differently.  Any guidance is appreciated.

**Comment by rjbs** [comment]
@lukec Can you provide a short program that demonstrates the problem?

It's okay to end up with vertical whitespace because of folding.  The warning should only be triggered if you do something like:

```perl
$email = Email::Simple->create(
  header => [ Subject => "contains \n vertical whitespace" ],
);
```

**Comment by lukec** [comment]
I see the warning with this short program.

```
#!/usr/bin/env perl
use 5.14.1; 
use Email::MIME;
use Email::MIME::CreateHTML;
use MIME::Base64;                                                               
        
my $subject = "Hello there this is a long subject line i like them better than the body of a email";
$subject = "=?utf-8?B?" . encode_base64($subject) . "?=";                       
    
Email::MIME->create_html(                                                       
    header => [
        From => 'luke@luke.luke',
        To   => 'rjbs@rjbs.rjbs',
        Subject => $subject,
    ],
    body => "Hello my friend",
);
```

v5.20.1
Email::MIME - 1.936
Email::MIME::CreateHTML - 1.041

**Comment by lukec** [comment]
So maybe we were doing something dumb?  We changed to using:

`Subject => Encode::encode('MIME-header', $subject)`, which uses base64 encoding only if necessary, and does not seem to trigger the warning....

**Comment by rjbs** [comment]
You are doing something erroneous.

```
  DB<1> use MIME::Base64 'encode_base64'

  DB<2> x encode_base64("I love quiche.")
0  'SSBsb3ZlIHF1aWNoZS4=
'
```

Note the line break at the end of the Base64-encoded string.

You have several options.  It is very unfortunate that CreateHTML seems to drop the `header_str` argument.  That's an alternative to `header` that will transparently encode all headers as needed.  That would've been my top suggestion, otherwise.

You could keep using Encode::encode.  Unfortunately, it has bugs regarding line breaking (see rt.cpan.org #40027).

So, what you did was fine, but you need to do this: `encode_base64($input, "")`

The empty second argument will use an empty string instead of a newline as the line break.  This will work.  I guess it's what I suggest, unless you want to provide a patch for CreateHTML to its maintainer. 😄

I hope this helps!

**Comment by lukec** [comment]
@rjbs thank you so much for this write-up. We'll try your suggestion and see how it works.  Thank you again.
